#! /bin/bash

# [Config]
source config

function help() {
    echo "usage: main.sh [<args>]"
    echo "args includes:"
    echo "    start:    Start the Application"
    echo "    stop:     Stop the Application"
    echo "    install:  Install the Application"
    echo "    help:     Get Help"
}

# [Shell]
if [ "$1" = "start" ]; then
    docker start ${SERVER_NAME}
elif [ "$1" = "install" ]; then
    docker build -t ${DOCKER_NAME}:${DOCKER_VERSION} App/Server/docker/ --rm \
        && docker run -itd -p ${DOCKER_PORT}:80 -v ${SMR_PATH}/Share:/Share -v ${SMR_PATH}/App/Server/html:/var/www/html --name ${SERVER_NAME} ${DOCKER_NAME}:${DOCKER_VERSION} \
        && docker start ${SERVER_NAME}
elif [ "$1" = "stop" ]; then
    docker stop ${SERVER_NAME}
elif [ "$1" = "help" ]; then
    help
else
    echo -e "\033[31mERROR Args\033[0m"
    help
fi