#! /bin/bash

# [Config]
source config

function help() {
    echo "usage: main.sh [<args>]"
    echo "args includes:"
    echo "    start:        Start the Application"
    echo "    stop:         Stop the Application"
    echo "    install:      Install the Application"
    echo "    uninstall:    Uninstall the Application"
    echo "    help:         Get Help"
}

function start() {
    docker start ${SERVER_NAME}
    docker start ${VI_NAME} \
        && docker exec -id ${VI_NAME} ./predict
    docker start ${LLR_NAME}
}

function stop() {
    docker stop ${SERVER_NAME}
    docker stop ${VI_NAME}
    docker stop ${LLR_NAME}
}

function install() {
    docker build -t ${SERVER_DOCKER_NAME}:${SERVER_DOCKER_VERSION} App/Server/docker/ --rm \
        && docker run -itd -p ${SERVER_DOCKER_PORT}:80 -v ${SMR_PATH}/Share:/Share -v ${SMR_PATH}/App/Server/html:/var/www/html --name ${SERVER_NAME} ${SERVER_DOCKER_NAME}:${SERVER_DOCKER_VERSION} \
        && docker start ${SERVER_NAME}

    docker build -t ${VI_DOCKER_NAME}:${VI_DOCKER_VERSION} App/Vehicle_Identification/docker/ --rm \
        && docker run -itd -v ${SMR_PATH}/Share:/Share -v ${SMR_PATH}/App/Vehicle_Identification/YOLOv3:/YOLOv3 --name ${VI_NAME} ${VI_DOCKER_NAME}:${VI_DOCKER_VERSION} \
        && docker start ${VI_NAME} \
        && docker exec -it ${VI_NAME} make clean \
        && docker exec -it ${VI_NAME} make \
        && docker exec -id ${VI_NAME} chmod a+x ./predict \
        && docker exec -id ${VI_NAME} ./predict

    docker build -t ${LLR_DOCKER_NAME}:${LLR_DOCKER_VERSION} App/Lane_Line_Recognition/docker --rm \
        && docker run -itd -v ${SMR_PATH}/Share:/Share -v ${SMR_PATH}/App/Lane_Line_Recognition/Hough:/Hough --name ${LLR_NAME} ${LLR_DOCKER_NAME}:${LLR_DOCKER_VERSION} \
        && docker start ${LLR_NAME}
}

function uninstall() {
    docker stop ${SERVER_NAME}
    docker rm ${SERVER_NAME}
    docker image rm ${SERVER_DOCKER_NAME}:${SERVER_DOCKER_VERSION}

    docker stop ${VI_NAME}
    docker rm ${VI_NAME}
    docker image rm ${VI_DOCKER_NAME}:${VI_DOCKER_VERSION}

    docker stop ${LLR_NAME}
    docker rm ${LLR_NAME}
    docker image rm ${LLR_DOCKER_NAME}:${LLR_DOCKER_VERSION}
}

# [Shell]
if [ "$1" = "start" ]; then
    start
elif [ "$1" = "install" ]; then
    install
elif [ "$1" = "uninstall" ]; then
    uninstall
elif [ "$1" = "stop" ]; then
    stop
elif [ "$1" = "help" ]; then
    help
else
    echo -e "\033[31mERROR Args\033[0m"
    help
fi