FROM fengodchen_seed_image:1.0
MAINTAINER LiaoChen <17211401@bjtu.edu.cn>

# Set Share Python Lib
RUN echo "export PYTHONPATH=/Share/PythonLib" >> /root/.bashrc

# Set Share File
RUN mkdir /Interface
WORKDIR /Interface