FROM fengodchen_seed_image:1.0
MAINTAINER LiaoChen <17211401@bjtu.edu.cn>

# Set Pyhton import Path
RUN echo "export ${PYTHONPATH}:PYTHONPATH=/Share/App/Socket_Operator" >> /root/.bashrc

# Set Share File
RUN mkdir /Hough

WORKDIR /Hough
